name: Export and Deploy to Itch.io

# This tells GitHub to run the script whenever you push to the 'main' branch
on:
  push:
    branches: [main]

jobs:
  export_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. This step downloads Godot and builds your game
      - name: Export Godot Project
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          # Swapped to GitHub release URLs to prevent rate-limiting!
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.6.3-stable/Godot_v4.6.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.6.3-stable/Godot_v4.6.3-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true

      - name: Copy archives to workspace
        run: |
          cp "${{ steps.export.outputs.archive_directory }}/Windows Desktop.zip" "${{ github.workspace }}/Windows Desktop.zip"
          cp "${{ steps.export.outputs.archive_directory }}/Web.zip" "${{ github.workspace }}/Web.zip"

      # 2. This step takes the built game and pushes it to Itch.io
      - name: Publish Windows Build to Itch.io
        uses: manleydev/butler-publish-itchio-action@v1.2.0
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: windows
          ITCH_USER: llnuggetsll
          ITCH_GAME: test-game
          PACKAGE: Windows Desktop.zip

      - name: Publish Web Build to Itch.io
        uses: manleydev/butler-publish-itchio-action@v1.2.0
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: html
          ITCH_USER: llnuggetsll
          ITCH_GAME: test-game
          PACKAGE: Web.zip
